# Generated by Django 2.1 on 2020-08-20 17:57

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_by',
            field=models.IntegerField(blank=True, null=True, verbose_name=network.models.User),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.IntegerField(blank=True, null=True, verbose_name=network.models.User),
        ),
    ]
