# Generated by Django 2.1 on 2020-08-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200820_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_by',
        ),
    ]
